package main

import (
	"bytes"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"

	"github.com/javadh75/SSHepherd/internal/config"
	"github.com/javadh75/SSHepherd/internal/identity"
	"github.com/javadh75/SSHepherd/internal/sshcfg"
)

// serverOut/userOut/accessOut mirror the config types for output: omitempty
// keeps default ports and never-set fields out of the generated YAML.
type serverOut struct {
	Name string `yaml:"name"`
	Host string `yaml:"host"`
	Port int    `yaml:"port,omitempty"`
	User string `yaml:"user"`
}

type userOut struct {
	Name        string   `yaml:"name"`
	Description string   `yaml:"description,omitempty"`
	Comment     string   `yaml:"comment,omitempty"`
	Keys        []string `yaml:"keys"`
}

type accessOut struct {
	User    string   `yaml:"user"`
	Servers []string `yaml:"servers"`
}

type manifestOut struct {
	Users   []userOut   `yaml:"users"`
	Servers []serverOut `yaml:"servers"`
	Access  []accessOut `yaml:"access"`
}

// generateManifest renders hosts and derived identity users as a manifest.
// src is the config path as the user typed it (kept in the header comment;
// the expanded form would leak the local home directory into a committed
// file). Hosts with no resolved User cannot form a valid server entry and are
// returned as skip notes instead. users may be nil (--servers-only).
func generateManifest(hosts []sshcfg.Host, users []identity.User, src string) ([]byte, []string, error) {
	m := manifestOut{Users: []userOut{}, Servers: []serverOut{}, Access: []accessOut{}}
	var skipped []string
	for _, h := range hosts {
		if h.User == "" {
			skipped = append(skipped, fmt.Sprintf(
				"host %q: no User resolved, skipped (the manifest requires user)", h.Alias))
			continue
		}
		s := serverOut{Name: h.Alias, Host: h.HostName, User: h.User}
		if h.Port != 0 && h.Port != 22 {
			s.Port = h.Port
		}
		m.Servers = append(m.Servers, s)
	}
	for _, u := range users {
		desc := "imported from " + u.Source
		if u.Default {
			desc += " (default identity)"
		}
		m.Users = append(m.Users, userOut{
			Name:        u.Name,
			Description: desc,
			Comment:     u.Comment,
			Keys:        []string{u.Key},
		})
		m.Access = append(m.Access, accessOut{User: u.Name, Servers: u.Servers})
	}
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "# generated by sshepherd import from %s — review before use\n", src)
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(m); err != nil {
		return nil, nil, fmt.Errorf("encode manifest: %w", err)
	}
	if err := enc.Close(); err != nil {
		return nil, nil, fmt.Errorf("encode manifest: %w", err)
	}
	return buf.Bytes(), skipped, nil
}

const defaultSSHConfig = "~/.ssh/config"

func newImportCmd(stdout io.Writer) *cobra.Command {
	var (
		outPath string
		force   bool
	)
	cmd := &cobra.Command{
		Use:   "import [ssh-config-path]",
		Short: "Convert an OpenSSH client config into a starter manifest (servers only)",
		Long: "Reads an OpenSSH client config (default ~/.ssh/config), resolves each\n" +
			"concrete Host to the HostName/Port/User that ssh would use, and emits a\n" +
			"valid SSHepherd manifest with the servers section filled in. Users and\n" +
			"access are left empty: an SSH config says how to connect, not who may\n" +
			"log in where. Warnings about skipped entries go to stderr.",
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			src := defaultSSHConfig
			if len(args) == 1 {
				src = args[0]
			}
			srcPath, err := expandHome(src)
			if err != nil {
				return err
			}
			hosts, warnings, err := sshcfg.Load(srcPath)
			if err != nil {
				return fmt.Errorf("load ssh config: %w", err) // wrapcheck: wrap at package boundary
			}
			stderr := cmd.ErrOrStderr()
			for _, w := range warnings {
				fmt.Fprintln(stderr, "warning:", w)
			}
			manifest, skipped, err := generateManifest(hosts, nil, src)
			if err != nil {
				return err
			}
			for _, s := range skipped {
				fmt.Fprintln(stderr, "warning:", s)
			}
			// Self-check: never emit a manifest our own loader would reject.
			if _, err := config.Parse(manifest); err != nil {
				return fmt.Errorf("bug: generated manifest fails validation: %w", err)
			}
			if outPath == "" {
				if _, err := stdout.Write(manifest); err != nil {
					return fmt.Errorf("write stdout: %w", err)
				}
				return nil
			}
			return writeFileNoClobber(outPath, manifest, force)
		},
	}
	cmd.Flags().StringVarP(&outPath, "output", "o", "", "write the manifest to this file instead of stdout")
	cmd.Flags().BoolVar(&force, "force", false, "allow --output to overwrite an existing file")
	return cmd
}

// writeFileNoClobber writes data to path with owner-only permissions,
// refusing to replace an existing file unless force is set.
func writeFileNoClobber(path string, data []byte, force bool) error {
	flags := os.O_WRONLY | os.O_CREATE | os.O_TRUNC
	if !force {
		flags = os.O_WRONLY | os.O_CREATE | os.O_EXCL
	}
	f, err := os.OpenFile(path, flags, 0o600) // #nosec G304 -- path is the user's own -o flag
	if err != nil {
		if os.IsExist(err) {
			return fmt.Errorf("%s already exists; pass --force to overwrite", path)
		}
		return fmt.Errorf("write %s: %w", path, err)
	}
	// The mode above only applies at creation; a --force overwrite via
	// O_TRUNC would keep the existing file's permissions, so pin them.
	if err := f.Chmod(0o600); err != nil {
		_ = f.Close()
		return fmt.Errorf("write %s: %w", path, err)
	}
	if _, err := f.Write(data); err != nil {
		_ = f.Close()
		return fmt.Errorf("write %s: %w", path, err)
	}
	if err := f.Close(); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}
